### ISSUE TITLE
Meet the UXers in your focus area

### ISSUE THREAD

**Issue by teddyba** [grafana/ux-onboarding#113]
Across the UX team, we work on different parts of the product. We are aligned with PMs and engineering teams by focus area. These are the designers who work in your focus area, Metrics, Logs, and Traces. You will work closely with them and meet to share ideas, discuss dependencies, and define the design direction for your area. 

- [x] Niat Hadgu (your buddy) - Germany
- [x] Diego Adams - South Africa
- [x] Pauric O'Callahan - Boston

**Comment by mary-sitzenstatter** [comment]
Amy Super 
Patrick O'Carroll
Staton Hysell
Natasha de Jesus
