### ISSUE TITLE
Meet your Product Manager

### ISSUE THREAD

**Issue by teddyba** [grafana/ux-onboarding#115]
At Grafana, we try to pair up UXDs and PMs - to work in the same problem space, but tackling it from 2 different angles, the PM from a strategic / customer / product-market fit perspective, and the UXD from a user-centric perspective. 

You will be working closely with Jen Villa, Jesse Weaver and Jay Goodson. Set up time to get to know them, discuss communication preferences, and figure out a cadence for recurring meetings with them. Many of our designers meet with their PMs on a weekly or bi-weekly basis. You may not need to do this with all of them as frequently - it's going to depend a lot on the projects you're working on at a given time. 

One other thing to note is that Jen recently transitioned to a management role and she will be building out a team. :)

- [x] Jen Villa
- [x] Jay Goodson
- [ ] Jesse Weaver (new PM, but not new to Grafana)

**Comment by teddyba** [comment]
@mary-sitzenstatter Please confirm that Catherine will be working with Jen.

**Comment by mary-sitzenstatter** [comment]
@teddyba - I would like to have her set up time with Jen and Jay - she will likely be working with both of them :)
