### ISSUE TITLE
Start joining your engineering team meetings

### ISSUE THREAD

**Issue by teddyba** [grafana/ux-onboarding#116]
Ask your buddy and/or your manager to add you to relevant engineering team meetings. Typically, engineering teams have either daily stand-ups or a weekly meeting to discuss progress, do planning, do the occasional retro, sometimes do design reviews, etc. 

We practice some agile practices, but we are not a strict agile shop. The way that engineering teams plan and track work varies from team to team.

**Comment by teddyba** [comment]
@mary-sitzenstatter We could suggest a few engineering team meetings that Catherine should get invites to.

**Comment by teddyba** [comment]
@niat22 suggest meetings!

**Comment by mary-sitzenstatter** [comment]
I'm still solidifying what projects Catherine will be working on, so holding off on this until I confirm with some of the EMs :)

**Comment by mary-sitzenstatter** [comment]
To start, you can shadow @niat22 with her team meetings :)
