### ISSUE TITLE
Join relevant slack channels

### ISSUE THREAD

**Issue by teddyba** [grafana/ux-onboarding#167]
Join Slack Grafana channels 
UX channels: 

- **#ux** - This is our public-facing channel. We typically use this for announcements to the org about UX, and async UX discussions.
- **#uxr-sandbox** - The sandbox is private - Your buddy and/or manager will invite you. This channel is for team banter, and for notifying the team when you will be out or offline. 
- **#ux-feedback-bot** - This channel is a donut-style channel where you get paired with another designer on the team every 2 weeks to meet up and share your work with one another. [Teddy Bartha](mailto:teddy.bartha@grafana.com) will add you, but it is totally optional!

Focus area channels:
- **#grafana-metrics**
- **#observability-logs**
- **#observability-traces-and-profiling**

Other: #grafana-observability, #announcements, #product, #community, **#grafana**, #general, #random, #design, #grafana-research, #cloud-research, #frontend, #accessibility, #docs, #data-and-analytics

Off work topics that might be interesting: #coffee, #pets-and-babies, #book-club, #climate, #biking, #maker, #music, #photography, #food-and-beverages, #toronto-grafanistas

Join #teatime to get randomly matched with other Grafanistas to meet for tea - optional (but totally fun and a great way to build relationships across the company)

**Comment by teddyba** [comment]
@niat22  - suggest any engineering team channels also!

**Comment by mary-sitzenstatter** [comment]
added some in @teddyba !
