### ISSUE TITLE
Connect with your UX buddy

### ISSUE THREAD

**Issue by teddyba** [grafana/ux-onboarding#84]
Talk with @niat22 about how you'd like to collaborate - frequency of meetings, preferred communication channels, etc.

It takes time to understand how work gets done at Grafana Labs - e.g. team and org structure, meetings, artifacts, etc. Your buddy is a great resource to ask questions - this is not someone who is monitoring you, but who is here to help you navigate the waters of Grafana!

**Comment by teddyba** [comment]
@mary-sitzenstatter Once we confirm if Catherine's buddy is Niat, we can tag her here.

**Comment by mary-sitzenstatter** [comment]
Confirming that @niat22 will be Catherine's buddy :)
