### ISSUE TITLE
Connect with your technical buddy

### ISSUE THREAD

**Issue by teddyba** [grafana/ux-onboarding#85]
Connect with Sarah Zinger - your technical buddy - if they haven't already reached out to you. 

Your technical buddy may or may not be someone who works on the engineering team you'll be joining. The technical buddy can help you:

- Understand how engineering is structured and works in Grafana
- Learn more about your engineering team and focus area (if they are working on the same team as you) 
- Support technical learning around Grafana the product, observability, etc. 
- Help you set up your local environment (if OSS/Enterprise) and/or get set up with a Grafana Cloud pro account and get added to specific orgs that have active applications and data so you can start playing around :)

**Comment by teddyba** [comment]
@mary-sitzenstatter Once we identify a technical buddy for Catherine, we will add their name here.

**Comment by mary-sitzenstatter** [comment]
Thanks! I am adding this to my list. I think we will want to get someone based in the US for this - I'm actually thinking that Kristina Durivage will be a good fit, but I need to check in with her :)

**Comment by mary-sitzenstatter** [comment]
@teddyba @niat22 - I updated this with Catherine's onboarding Buddy (@sarahzinger)
